name: ServerControlReloaded
main: me.DevTec.ServerControlReloaded.SCR.Loader
version: 7.9.7
website: https://www.spigotmc.org/resources/71147/
description: Fully customizable plugin with many features!
author: DevTec
depend: [TheAPI]
loadbefore: [WorldGuard,Residence,MobArena,SpecializedCrates,GoldenCrates]
softdepend: [Essentials,WorldEdit,LuckPerms]
api-version: 1.13