name: ServerControlReloaded
main: me.devtec.servercontrolreloaded.scr.Loader
version: 8.2
website: https://www.spigotmc.org/resources/71147/
description: Fully customizable plugin with many features!
author: DevTec
depend: [TheAPI]
loadbefore: [Paintball,WorldGuard,Residence,MobArena,SpecializedCrates,GoldenCrates,RevoltCrates,AdvancedMonthlyCrates,CrazyCrates,CrateReloaded]
softdepend: [Essentials,WorldEdit,LuckPerms]
api-version: 1.13