name: ServerControlReloaded
main: me.DevTec.ServerControlReloaded.SCR.Loader
version: 7.9.6
website: https://www.spigotmc.org/resources/71147/
description: Fully customizable plugin with many features!
author: DevTec
depend: [TheAPI]
loadbefore: [MobArena,SpecializedCrates,GoldenCrates]
softdepend: [Essentials,Residence,WorldGuard,WorldEdit]
api-version: 1.13