name: ServerControlReloaded
main: ServerControl.Loader
version: 7.7
website: https://www.spigotmc.org/resources/server-control-reloaded.71147/
description: Fully customizable plugin with many features!
author: DevTec
depend: [TheAPI]
softdepend: [Essentials,AFKPlus]
api-version: 1.13