name: ServerControlReloaded
main: ServerControl.Loader
version: 7.1.5
website: https://www.spigotmc.org/resources/server-control-reloaded.71147/
description: Fully customizable plugin with many features!
author: DevTec
depend: [TheAPI]
softdepend: [Vault]
api-version: 1.13
commands:
    Tpcancel:
        usage: /<command>
        description: Cancel teleportation
        aliases: [tpacancel]
    TempFly:
        usage: /<command> <player> <time> 
        description: Enable fly to player on time
    Suicide:
        usage: /<command>
        description: Kill yourself
    HomeOther:
        usage: /<command> <player> <home>
        description: Teleport you to player home
    CloseInv:
        usage: /<command> <player>
        description: Close player inventory
        aliases: [closeinventory, closeopeninv, closeopeninventory]
    TempBanIP:
        usage: /<command>
        description: Temp Ban IP adress or player
    Immune:
        usage: /<command>
        description: Immunity against ban
    WhoIs:
        usage: /<command> <player>
        description: Information about specified player
    NickReset:
        usage: /<command> <player>
        aliases: [nicknamereset]
        description: Reset nickname of player
    Nick:
        usage: /<command> <nickname>
        aliases: [nickname]
        description: Change your nickname
    Exp:
        usage: /<command>
        aliases: [xp, experiences]
        description: Manager for player experiences
    ChatFormat:
        usage: /<command>
        description: Main command to manage chat format
    Skull:
        usage: /<command> <name>
        description: Gave you player head
    Addons:
        description: Show you hooked addons
        usage: /<command>
    Jail:
        description: Jail player with reason
        usage: /<command> <player> <reason>
    unJail:
        description: unJail player
        usage: /<command> <player>
    setJail:
        description: Create new jail
        usage: /<command> <name>
    delJail:
        description: Remove existing jail
        usage: /<command> <name>
    unWarn:
        description: unWarn player
        usage: /<command> <player>
    Give:
        description: Give player item/block
        usage: /<command> <player> <item/block> <amount>
        aliases: [i]
    Butcher:
        description: Kill specified mobs in specified radious
        usage: /<command> <radius> <mob>
    Kill:
        description: Kill player
        usage: /<command> <player>
    KillAll:
        description: Kill all players
        usage: /<command>
    Tp:
        description: Teleport you to specified player
        usage: /<command> <player>
    Broadcast:
        description: Teleport you to specified player
        usage: /<command>
        aliases: [bc]
    Spawner:
        description: Sets spawner on specified entity
        usage: /<command> <mob>
    Hat:
        description: Set on your head item/block in your hand
        usage: /<command>
    Item:
        description: Main command for item editor
        usage: /<command>
    Tpa:
        description: Send request to specified player for teleport to him
        usage: /<command> <player>
    MultiEconomy:
        description: Main command to manage multi economies feature
        usage: /<command>
        aliases: [multieco]
    Tpaccept:
        description: Accept teleport request
        usage: /<command>
        aliases: [tpyes]
    TpBlock:
        description: Block or Unblock all requests for teleport of specified player
        usage: /<command> <player>
        aliases: [tpablock, tpaignore, tpignore, tptoggle, tpatoggle]
    Tpadeny:
        description: Deny teleport request
        usage: /<command>
        aliases: [tpno, tpdeny]
    Thor:
        description: Strike player with lighting bolt
        usage: /<command>
        aliases: [strike, smite,lighting]
    Tphere:
        description: Teleport to you specified player
        usage: /<command> <player>
    Sudo:
        description: Send message/command as specified player
        usage: /<command> <player> <arguments>
    Tpahere:
        description: Send request to specified player for teleport him to you
        usage: /<command> <player>
    Tpaall:
        description: Send request to all players for teleport to you
        usage: /<command>
    Tpall:
        description: Teleport all players to you
        usage: /<command>
    Kick:
        description: Kick specified player with reason
        usage: /<command> <player> <reason>
    Seen:
        description: Show you how long is player online/offline
        usage: /<command> <player>
    Ban:
        description: Ban specified player with reason
        usage: /<command> <player> <reason>
    Craft:
        description: Open virtual crafting table
        usage: /<command>
        aliases: [workbench,wb]
    Trash:
        description: Open virtual trash
        usage: /<command>
    Enchant:
        description: Add or Remove specified enchant to item in your hand
        usage: /<command> <enchant> <level>
        aliases: [enchanttable, enchantment]
    Staff:
        description: Shows online staff
        usage: /<command>
    EnchantRemove:
        description: Remove specified enchant from item in your hand
        usage: /<command> <enchant>
        aliases: [enchanttableremove, enchantmentremove]
    EnchantRemoveAll:
        description: Remove all enchants from item in your hand
        usage: /<command>
        aliases: [enchanttableremoveall, enchantmentremoveall]
    Enderchest:
        description: Open your virtual EnderChest
        usage: /<command>
        aliases: [echest]
    Endersee:
        description: Open virtual EnderChest of specified player
        usage: /<command> <player>
        aliases: [esee]
    Invsee:
        description: Open inventory of specified player
        usage: /<command> <player>
    Warn:
        description: Warn online or offline player with reason
        usage: /<command> <player> <reason>
    UnBan:
        description: UnBan specified player
        usage: /<command> <player>
        aliases: [pardon]
    TempBan:
        description: Temp Ban specified player for time with reason
        usage: /<command> <player> <time> <reason>
    Mute:
        description: Mute specified player with reason
        usage: /<command> <player> <reason>
    TempMute:
        description: Temp Mute specified player for time with reason 
        usage: /<command> <player> <time> <reason>
    UnMute:
        description: UnMute specified player
        usage: /<command> <player>
    Ban-IP:
        description: Ban IP adress of specified player with reason
        usage: /<command> <player> <reason>
        aliases: [ip-ban, ipban, banip]
    UnBan-IP:
        description: UnBan IP adress of specified player
        usage: /<command> <player>
        aliases: [unip-ban, unbanip, unipban, pardon-ip]
    SCR:
        description: Main plugin commands
        usage: /<command>
        aliases: [servercontrolreloaded, servercontrol]
    Chunks:
        description: Shows loaded chunks and worlds
        usage: /<command>
    RAM:
        description: Shows ram usage
        usage: /<command>
        aliases: [mem]
    Chat:
        description: Normal commands
        usage: /<command>
    Reply:
        description: Reply to private message
        usage: /<command> <message>
        aliases: [r]
    pm:
        description: Send private message to player
        usage: /<command> <player> <message>
        aliases: [message,m,w,tell,msg]
    Gamemode:
        description: Change your or other player gamemode
        usage: /<command>
        aliases: [gm]
    Gms:
        description: Change your or other player gamemode to survival
        usage: /<command>
    Gmc:
        description: Change your or other player gamemode to creative
        usage: /<command>
    Gmsp:
        description: Change your or other player gamemode to spectator
        usage: /<command>
    Gma:
        description: Change your or other player gamemode to adventure
        usage: /<command>
    Day:
        description: Set time to day
        usage: /<command> <world>
    Night:
        description: Set time to night
        usage: /<command> <world>
    ClearChat:
        description: Clear global chat or chat specified player
        usage: /<command> <player>
        aliases: [cc]
    ChatLock:
        description: Lock or unlock global chat
        usage: /<command>
        aliases: [lockchat]
    Back:
        description: Teleport you to latest position
        usage: /<command>
        aliases: [return]
    List:
        description: Shows online players in list
        usage: /<command>
        aliases: [who, online,players]
    Maintenance:
        description: Enable or Disable server maintenance mode
        usage: /<command>
    Vanish:
        description: Hide or Show you for all players
        usage: /<command> <player>
        aliases: [v]
    Clear:
        description: Clear your inventory and more
        usage: /<command>
        aliases: [clearinv, clearinvent, clearinventory]
    Heal:
        description: Heal you or specified player
        usage: /<command> <player>
    Board:
        description: Reload scoreboard config
        usage: /<command>
        aliases: [scs]
    God:
        description: Turns god mode on or off for you or specified player
        usage: /<command> <player>
    TPS:
        description: Get server TPS in real time
        usage: /<command>
        aliases: [lag]
    Repair:
        description: Repair item in your hand or all items in your inventory
        usage: /<command> <hand/all>
        aliases: [fix]
    Feed:
        description: Feed you or specified player
        usage: /<command> <player>
    Fly:
        description: Turns fly on or off for you or specified player
        usage: /<command> <player>
    FlySpeed:
        description: Set fly speed specified player
        usage: /<command> <player> <number>
    WalkSpeed:
        description: Set walk speed specified player
        usage: /<command> <player> <number>
    MultiWorlds:
        description: Main command for MultiWorlds commands
        aliases: [mw, multiworld]
        usage: /<command>
    TabList:
        description: Main command for TAB commands
        usage: /<command>
        aliases: [tab]
    Spawn:
        description: Teleport you to global spawn
        usage: /<command>
    SetSpawn:
        description: Set global spawn
        usage: /<command>
    Warp:
        description: Teleport you to existing warp
        usage: /<command> <warp>
        aliases: [warps]
    Home:
        description: Teleport you to home
        usage: /<command> <home>
    SetHome:
        description: Create new home
        usage: /<command> <home>
    DelHome:
        description: Delete existing home
        usage: /<command> <home>
    SetWarp:
        description: Create new warp
        usage: /<command> <warp>
    DelWarp:
        description: Delete existing warp
        usage: /<command> <warp>
    Homes:
        description: Shows you list of your homes
        usage: /<command>
    BalanceTop:
        description: Shows top 10 players balance
        usage: /<command>
        aliases: [baltop]
    Money:
        description: Main command for Economy commands
        usage: /<command>
        aliases: [eco, balance]
    Pay:
        description: Pay money to specified player
        usage: /<command>
    Sun:
        description: Set weather sunny
        usage: /<command> <wo
    Rain:
        description: Set weather rainy
        usage: /<command> <world>
    Strorm:
        description: Set weather rainy with storm
        usage: /<command> <world>
        aliases: [thunder]
    AFK:
        description: Turns on or off afk
        usage: /<command>
        aliases: [away]
    Helpop:
        description: Send message to online admins
        usage: /<command> <message>
        aliases: [ac, amsg]
    Kit:
        description: Shows you all existing kits and give you specified kit
        usage: /<command>
        aliases: [kits]
    ClearConfirmToggle:
        description: Toggle confirm in clear inventory commands
        usage: /<command>
        aliases: [clearinvconfirmtoggle, clearinventoryconfirmtoggle]
permissions:
    ServerControl.*:
        default: op
        description: Gives access to all commands
        children:
          ServerControl.Teleport.*: true
          ServerControl.Helpop.*: true
          ServerControl.Gamemode.*: true
          ServerControl.AFk.*: true
          ServerControl.Home.*: true
          ServerControl.Economy.*: true
          ServerControl.ClearInv.*: true
          ServerControl.God.*: true
          ServerControl.Heal.*: true
          ServerControl.Fly.*: true
          ServerControl.MultiWorld.*: true
          ServerControl.Give.*: true
    ServerControl.ClearInv.*:
        default: false
        children:
          ServerControl.ClearInv.Help: true
          ServerControl.ClearInv.Clear: true
          ServerControl.ClearInv.Other: true
          ServerControl.ClearInv.Clear: true
          ServerControl.ClearInv.Undo: false
    ServerControl.Teleport.*:
        default: false
        children:
          ServerControl.TpaAll.Blocked: true
          ServerControl.TpaAll: true
          
          ServerControl.TpaaAll: true
          
          ServerControl.TpaBlock: true
          
          ServerControl.Tpa: true
          ServerControl.Tpahere: true
          
          ServerControl.Tphere: true
          ServerControl.Tphere.Blocked: true
        
    ServerControl.Jail.*:
        default: false
        children:
          ServerControl.setJail: true
          ServerControl.Jail: true
          ServerControl.delJail: true
          ServerControl.unJail: true
            
    ServerControl.Economy.User:
        default: false
        children:
          ServerControl.Pay: true
          ServerControl.Balance: true
          ServerControl.Balance.Other: true
          ServerControl.BalanceTop: true
    ServerControl.Economy.*:
        default: false
        children:
          ServerControl.Economy.Take: true
          ServerControl.Economy.User: true
          ServerControl.Economy.Give: true
          ServerControl.Economy.Reset: true
    ServerControl.Heal.*:
        default: false
        children:
          ServerControl.Heal.Bypass: false
          ServerControl.Heal: true
          ServerControl.Heal.Other: false
    ServerControl.Home.*:
        default: false
        children:
          ServerControl.SetHome: true
          ServerControl.Home: true
          ServerControl.DelHome: true
    ServerControl.Helpop.*:
        default: false
        children:
          ServerControl.Helpop: true
          ServerControl.Helpop.Receive: true
    ServerControl.AFk.*:
        default: false
        children:
          ServerControl.Afk.Bypass: true
          ServerControl.Afk: true
    ServerControl.God.*:
        default: false
        children:
          ServerControl.God.OnJoin: true
          ServerControl.God: true
          ServerControl.God.Other: false
    ServerControl.Time.*:
        default: false
        children:
          ServerControl.Day: true
          ServerControl.Night: true
    ServerControl.Fly.*:
        default: false
        children:
          ServerControl.Fly.OnJoin: true
          ServerControl.Fly: true
          ServerControl.Fly.Other: false
    ServerControl.Economy.InMinus:
        default: false
    ServerControl.CooldownBypass:
        default: false
        children:
          ServerControl.CooldownBypass.Commands: true
          ServerControl.CooldownBypass.Chat: true
    ServerControl.Me:
        default: true
    ServerControl.Gamemode.*:
        default: op
        children:
          ServerControl.Gamemode: true
          ServerControl.Gamemode.Other: true
          ServerControl.Gamemode.Survival: true
          ServerControl.Gamemode.Specator: true
          ServerControl.Gamemode.Creative: true
          ServerControl.Gamemode.Adventure: true
    ServerControl.Multiworld.*:
        default: op
        children:
          ServerControl.MultiWorld.Set: true
          ServerControl.MultiWorld.Create: true
          ServerControl.MultiWorld.Delete: true
          ServerControl.MultiWorld.SetSpawn: true
          ServerControl.MultiWorld.Info: true
          ServerControl.MultiWorld.Tp: true
          ServerControl.MultiWorld.Import: true
          ServerControl.MultiWorld.Load: true
          ServerControl.MultiWorld.Unload: true