Enabled: false

# List of forbidden worlds
ForbiddenWorlds:
- "DisabledWorld"

PerPlayer:
  InputPlayerNameHere:
    Toggleable: true
    Text: "&e&l%animation-welcome% &6%playername%"
    
PerWorld:
  InputWorldNameHere:
    Toggleable: true
    Text: "&e&l%animation-welcome% &6%playername%"

Toggleable: true

# Reflesh speed in ticks
RefleshTick: 20

# ActionBar text
Text: "&e&l%animation-welcome% &6%playername%"