Enabled: false

Permission: "SCR.See.BossBar"

# List of forbidden worlds
ForbiddenWorlds:
- "DisabledWorld"

PerPlayer:
  InputPlayerNameHere:
    Toggleable: true
    Stage: '100.0'
    Text: "&e&l%animation-welcome% &6%playername%"
    Type: "PROGRESS"
    Color: "GREEN"
    
PerWorld:
  InputWorldNameHere:
    Toggleable: true
    Stage: '100.0'
    Text: "&e&l%animation-welcome% &6%playername%"
    Type: "PROGRESS"
    Color: "GREEN"

Toggleable: true

# Reflesh speed in ticks
RefleshTick: 20

# BossBar stage (Can be used %math{}% !}
Stage: '100.0'

# BossBar type (Types: NOTCHED_10, NOTCHED_12, NOTCHED_20, NOTCHED_6, PROGRESS)
Type: "PROGRESS"

# BossBar color (Colors: RANDOM, GREEN, BLUE, PINK, PURPLE, RED, WHITE, YELLOW)
Color: "RANDOM"

# BossBar text
Text: "&e&l%animation-welcome% &6%playername%"