# ░█████╗░██████╗░███████╗░█████╗░████████╗███████╗██████╗░  ██████╗░██╗░░░██╗  ██████╗░███████╗██╗░░░██╗████████╗███████╗░█████╗░
# ██╔══██╗██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔════╝██╔══██╗  ██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔════╝██║░░░██║╚══██╔══╝██╔════╝██╔══██╗
# ██║░░╚═╝██████╔╝█████╗░░███████║░░░██║░░░█████╗░░██║░░██║  ██████╦╝░╚████╔╝░  ██║░░██║█████╗░░╚██╗░██╔╝░░░██║░░░█████╗░░██║░░╚═╝
# ██║░░██╗██╔══██╗██╔══╝░░██╔══██║░░░██║░░░██╔══╝░░██║░░██║  ██╔══██╗░░╚██╔╝░░  ██║░░██║██╔══╝░░░╚████╔╝░░░░██║░░░██╔══╝░░██║░░██╗
# ╚█████╔╝██║░░██║███████╗██║░░██║░░░██║░░░███████╗██████╔╝  ██████╦╝░░░██║░░░  ██████╔╝███████╗░░╚██╔╝░░░░░██║░░░███████╗╚█████╔╝
# ░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═════╝░  ╚═════╝░░░░╚═╝░░░  ╚═════╝░╚══════╝░░░╚═╝░░░░░░╚═╝░░░╚══════╝░╚════╝░
#
# Links:
#  Github: https://github.com/TheDevTec/ServerControlReloaded
#  Discord: https://discord.io/spigotdevtec
#  Spigot: https://www.spigotmc.org/resources/71147/

Options:
  # cz, sk, en
  Language: "en"
  
  Skins:
    # Load default skin on join
    onJoin: true
    Custom:
      # Default skin of player
      default: "%player%"
      setOwnToAll:
        set: false
        # Skin name or url
        value: "StraikerinaCZ"
        
  PacketLimiter:
    Use: true
    Limit: 2
  
  Chat:
    # Types: GLOBAL, PER_WORLD, DISTANCE
    Type: "GLOBAL"
    # 50 blocks - only for chat type "distance"
    Distance: 50
  
  ChatNotification:
    Enabled: true
    Color: "&c"
    Sound: "ENTITY_PLAYER_LEVELUP"
    Title: "&eSomeone tagged you in a chat"
    SubTitle: ""
    ActionBar: "&eSomeone tagged you in a chat"
    
  LockChat:
    Helpop: true
    PrivateMessage: true
    
  # Remove line from list broadcast, if joiner is empty
  List-RemoveEmptyLine: true
  
  Staff:
    # if staff is empty
    HideAllLines: true
    # If is enabled HideAllLines
    UseReplace: true
    ReplaceWith:
    - "%prefix% Anyone from staff is online"
    
  ChatLock: false
  
  FarmingSystem:
    Use: true
    ForbiddenWorlds:
    - "spawn"
    
  SinglePlayerSleep: true
  
  # ActionBar when you have enabled vanish
  Vanish-ActionBar: true
  
  RAM-Percentage: false
  
  AntiSpam:
    SimiliarMessage: true
    DoubleLetters: true
    
  AntiCaps:
    Chat: true
    Commands: false
  
  # SPAWN, HOME, BED
  RespawnTeleport: "HOME"
  Use-RespawnTeleport: true
  
  TimeZone:
    Use: false
    # https://greenwichmeantime.com/time-zone
    Zone: "Europe/Prague"
    
  Sounds:
    Use: false
    Sound: "ENTITY_PLAYER_LEVELUP"
    
  Teleport:
    RequestTime: "1min"
    CommandSendLocation: false
    SafeLocation: true
    
  AFK:
    AutoAFK: true
    AutoKick: true
    TimeToAFK: "5min"
    TimeToKick: "10min"
    # List of commands
    Action:
      onStartAFK: []
      onStopAFK: []
      onKickAFK:
      - "kick %player% &7You were kicked for &eAFK &7longer than 15 minutes"
    
  Economy:
    Money: 250.0
    DisablePluginEconomy: false
    CanUseOtherEconomy: true
    BalanceTop: "&e%position%. &7%playername% &7(&e$%money%&7)"
    Log: false
    MultiEconomy:
      Use: false
      Types:
        default:
        - "world"
        - "world_nether"
        - "world_the_end"
        
  WarningSystem:
    Reload:
      Use: true
      PauseTime: 5
      Process:
      - "&8****** &4Reload &8******"
      - "&7Server is reloading..."
      - "&8****** &4Reload &8******"
      Cancelled:
      - "&8****** &4Reload &8******"
      - "&7Server reload cancelled"
      - "&8****** &4Reload &8******"
      Messages:
      - "&8****** &4Reload &8******"
      - "&7Reloading of server in &e%time%"
      - "&8****** &4Reload &8******"
    Restart:
      Use: true
      PauseTime: 15
      Process:
      - "&8****** &4Restart &8******"
      - "&7Server is restarting..."
      - "&8****** &4Restart &8******"
      Cancelled:
      - "&8****** &4Restart &8******"
      - "&7Server restart cancelled"
      - "&8****** &4Restart &8******"
      Messages:
      - "&8****** &4Restart &8******"
      - "&7Restart of server in &e%time%"
      - "&8****** &4Restart &8******"
      Commands:
      - "send * lobby"
      Kick: "&cServer is restarting"
    Stop:
      Use: true
      PauseTime: 15
      Process:
      - "&8****** &4Shutdown &8******"
      - "&7Shutting down the server..."
      - "&8****** &4Shutdown &8******"
      Cancelled:
      - "&8****** &4Shutdown &8******"
      - "&7Server shutdown cancelled"
      - "&8****** &4Shutdown &8******"
      Messages:
      - "&8****** &4Shutdown &8******"
      - "&7Shutdown of server in &e%time%"
      - "&8****** &4Shutdown &8******"
      Commands:
      - "send * lobby"
      Kick: "&cServer closed"
      
  AutoMessage:
    Use: true
    MinimalPlayers: 1
    Interval: "5min"
    Random: true
    # - "{"text":"&0[&e&lINFO&0] &7ServerControlReloaded created by &nDevTec"}"
    UseJson: false
    Messages:
    - "&0[&e&lINFO&0] &7ServerControlReloaded created by &nDevTec"
    - "&0[&e&lINFO&0] &720% Bugs free"
    - "&0[&e&lINFO&0] &7Online players &e%online%&7/&e%max_players%"
    - "&0[&e&lINFO&0] &7You found a bug ? Report it to https://github.com/TheDevTec/ServerControlReloaded"
    - "&0[&e&lINFO&0] &7Do you like our plugin? Write a comment on the https://www.spigotmc.org/resources/71147"
    
  ServerList:
    MOTD:
      Use: true
      # If is enabled maintenance mode, change motd to Maintenance motd
      Maintenance: false
      Text:
        Normal: "&7&l====» &eMinecraft Server%line%&7&lOnline players: &e%server_online%/%server_max_online%"
        Maintenance: "&7&l====» &eMinecraft Server%line%&eServer is under maintenance mode"
        
  VIPSlots:
    Use: true
    AddSlots: false
    SlotsToAdd: 5
    KickWhenFullServer: true
    VIPJoinBroadcast: false
    Text:
      Kick: "&7Buy &eVIP &7on our website and get access to this &ereserved slot"
      BroadcastVIPJoin: "&eVIP player joined to the server"
      FullServer: "&7We are sorry, but all &eVIP Slots &7are in use"
      
  Cooldowns:
    Chat:
      Use: true
      Time: 2
    Commands:
      Use: true
      Time: 3
      PerCommand:
        Use: true
        # Command:Time
        List:
        - "Heal:300"
        - "Feed:150"
        
  CommandsBlocker:
    Use: true
    List:
    - "pl"
    - "version"
    - "ihasbukkit"
    - "spigot"
    
  StaffList:
  - "owner"
  - "admin"
  - "helper"
  - "builder"
  
  Colors:
    Sign:
      Use: true
      Required-Permission: true
      Permission:
        Gradient: "SCR.Other.Sign.Gradient" 
        Color: "SCR.Other.Sign.Color"
        Format: "SCR.Other.Sign.Format"
        Magic: "SCR.Other.Sign.Magic"
        Rainbow: "SCR.Other.Sign.Rainbow"
        HEX: "SCR.Other.Sign.HEX"
    Chat:
      Use: true
      Required-Permission: true
      Permission:
        Gradient: "SCR.Other.Chat.Gradient"
        Color: "SCR.Other.Chat.Color"
        Format: "SCR.Other.Chat.Format"
        Magic: "SCR.Other.Chat.Magic"
        Rainbow: "SCR.Other.Chat.Rainbow"
        HEX: "SCR.Other.Chat.HEX"
        
  Maintenance:
    Enabled: false
    KickMessages:
    - "&8=-=-=-=-=-= &eMaintenance Mode &8=-=-=-=-=-="
    - "&7We are sorry &e%player%&7, the server is currently under maintenance mode"
    - "&7Website: &ewww.example.com"
    - "&7Discord: &ediscord.link"
    
  Codes:
    Use: false
    Message: "%prefix% &7Congratulation, you found secret code: &e%code%"
    List:
    - "ServerControlReloaded"
    - "TheAPI"
    - "DevTec"
    - "2019"
    Random-Command:
    - "eco give %player% 50"
    - "eco give %player% 150"
    - "give %player% diamond 2"
    - "give %player% iron_block 1"
    - "xp give %player% 150"
    Commands:
    - "eco give %player% 25"
    
  Disallowed-Items:
    Use: false
    Worlds:
   #   Creative: 
   #   - "Bedrock"
   #   - "TNT"
   #   - "TNT_Minecart"
      world:
      -  "Bedrock"
      world_nether:
      - "Bedrock"
      world_the_end:
      - "Bedrock"
      
BanSystem:
  TempMute:
    Text: "&7You are temp-muted for &e%reason%&7 on &e%time%"
    Time: "1h"
    Reason: "None"
  Mute:
    Text: "&7You are muted for &e%reason%"
    Reason: "None"
  Ban:
    Text: "&7You are banned for &e%reason%\n&7www.example.com"
    Reason: "None"
  TempBan:
    Text: "&7You are temp-banned for &e%reason%&7 on &e%time%\n&7www.example.com"
    Time: "1h"
    Reason: "None"
  Kick:
    Text: "&7You are kicked for &e%reason%\n&7www.example.com"
    Reason: "None"
  BanIP:
    Text: "&7You are ip-banned for &e%reason%\n&7www.example.com"
    Reason: "None"
  TempBanIP:
    Text: "&7You are temp-ip-banned for &e%reason%&7 on &e%time%\n&7www.example.com"
    Reason: "None"
    Time: "1h"
  TempJail:
    Text: "&7You are temp-arrested for &e%reason%&7 on &e%time%"
    Time: "1h"
    Reason: "None"
  Jail:
    Text: "&7You are arrested for &e%reason%"
    Reason: "None"
  Warn:
    Text: "&7You are warned for &e%reason%"
    Reason: "None"
    
ChatFormat:
  global:
    options:
      enabled: true
      json: false
    chat: "&f<%playername%&f&r> %message%"
    name: "%player%"
 # group:
 #   default:
 #     options:
 #       enabled: true
 #       json: false
 #     chat: "%playername% &8> &f%message%"
 #     name: "&7default &f%player%"
 # user:
 #  <nickname>:
 #    options:
 #      enabled: true
 #      json: false
 #    chat: "%playername% &8> &e%message%"
 #    name: "&cCustom&4Prefix &b%player%"
 #  group:
 #    <group>:
 #      options:
 #        enabled: true
 #        json: false
 #      chat: "%playername% &8> &5%message%"
 #      name: "&dHelper &9%player%"
 # world:
 #  <world>:
 #    options:
 #      enabled: true
 #      json: false
 #    global:
 #      chat: "%playername% &8> &d%message%"
 #      name: "&0[&b%world%&0] &3%player%"
 #    user:
 #      <nickname>:
 #        options:
 #          enabled: true
 #          json: false
 #        chat: "%playername% &8> &e%message%"
 #        name: "&cCustom&4Prefix &b%player%"
 #    group:
 #      <group>:
 #        options:
 #          enabled: true
 #          json: false
 #        chat: "%playername% &8> &3%message%"
 #        name: "&cAdmin &6%player%"

Homes:
  #GroupName: amount
  default: 3
 # vip: 5
 # owner: 10 

# Types: REGEX, CONTAINS, EQUALS, STARTS_WITH, ENDS_WITH
# Regex flags: CASE_INSENSITIVE, COMMENTS, CANON_EQ, DOTALL, LITERAL, MULTILINE, UNICODE_CASE, UNICODE_CHARACTER_CLASS, UNIX_LINES
Rules:
  antiSwear_idiot:
    # Example: "What an idiot" -> "What an good boy"
    Type: "REGEX"
    # idiot -> 1d1ot -> 1d10t
    Text: "[i1]+[ ]*[d]+[ ]*[i1]+[ ]*[o0]+[ ]*[t]+"
    Replacement:
      Use: true
      # replace word "idiot" with "*****"
      Text: "*****"
 # antiSpam_d:
 #   Type: "REGEX"
 #   Text: "d{5}"
 #   Replacement:
 #     Use: true
 #     Text: "d"
 # antiAd_ip:
 #   Type: "REGEX"
 #   Text: "[0-9]+[. ][0-9]+[. ][0-9]+[. ][0-9]+(:[0-9]+)*"
 #   Replacement:
 #     Use: false
 #     Text: "ANTIAD"
 # antiAd_web:
 #   Type: "REGEX"
 #   Text: "([A-z]{2,20}\.)*[A-z]{2,100}\.[A-z]{2,20}[:]*[0-9]*"
 #   Replacement:
 #     Use: false
 #     Text: "ANTIAD"

Format:
  SocialSpy: "&a[&2SP | &6%player% &8>> &e%target%&a] &d%message%"
  Mail: "&e%player% &7: &e%message%"
  Time: "HH:mm:ss"
  Date: "dd.MM.yyyy"
  DateWithTime: "dd.MM.yyyy HH:mm:ss"
  Broadcast: "&0[&4Broadcast&0] &a%message%"
  PrivateMessageTo: "&8(&7You -> &e%to%&8)&7: &e%message%"
  PrivateMessageFrom: "&8(&e%from% -> &7You&8)&7: &e%message%"
  HelpOp: "&0[&4HelpOp&0] &7%sender%&7: &c%message%"

CountryBlocker:
  Enabled: false
  List:
    - "us"
    - "se"
    - "de"
  Whitelist:
    - "petulikan1"
    - "StraikerinaCZ"
  KickMessage: "&cYour country is currently blocked! &eContact admins for whitelist"
