# ░█████╗░██████╗░███████╗░█████╗░████████╗███████╗██████╗░  ██████╗░██╗░░░██╗  ██████╗░███████╗██╗░░░██╗████████╗███████╗░█████╗░
# ██╔══██╗██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔════╝██╔══██╗  ██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔════╝██║░░░██║╚══██╔══╝██╔════╝██╔══██╗
# ██║░░╚═╝██████╔╝█████╗░░███████║░░░██║░░░█████╗░░██║░░██║  ██████╦╝░╚████╔╝░  ██║░░██║█████╗░░╚██╗░██╔╝░░░██║░░░█████╗░░██║░░╚═╝
# ██║░░██╗██╔══██╗██╔══╝░░██╔══██║░░░██║░░░██╔══╝░░██║░░██║  ██╔══██╗░░╚██╔╝░░  ██║░░██║██╔══╝░░░╚████╔╝░░░░██║░░░██╔══╝░░██║░░██╗
# ╚█████╔╝██║░░██║███████╗██║░░██║░░░██║░░░███████╗██████╔╝  ██████╦╝░░░██║░░░  ██████╔╝███████╗░░╚██╔╝░░░░░██║░░░███████╗╚█████╔╝
# ░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═════╝░  ╚═════╝░░░░╚═╝░░░  ╚═════╝░╚══════╝░░░╚═╝░░░░░░╚═╝░░░╚══════╝░╚════╝░
#
# Links:
#  Github: https://github.com/TheDevTec/ServerControlReloaded
#  Discord: https://discord.io/spigotdevtec
#  Spigot: https://www.spigotmc.org/resources/71147/

Options:
  # cz, sk, en
  Language: "en"

  Skins:
    # Hook dynmap support for web heads?
    DynmapSupport: true
    # Load default skin on join
    onJoin: true
    Custom:
      # Default skin of player
      default: "%player%"
      setOwnToAll:
        set: false
        # Skin name or url
        value: "StraikerinaCZ"

  PacketLimiter:
    Use: true
    Limit: 2

  Chat:
    # Types: GLOBAL, PER_WORLD, DISTANCE
    Type: "GLOBAL"
    # 50 blocks - only for chat type "distance"
    Distance: 50

  ChatNotification:
    Enabled: true
    Color: "&c"
    Sound: "ENTITY_PLAYER_LEVELUP"
    Title: "&eSomeone tagged you in a chat"
    SubTitle: ""
    ActionBar: "&eSomeone tagged you in a chat"
    # Placeholder: %pinged%
    Commands: []
    # Placeholder: %pinged%
    Messages: []

  LockChat:
    Helpop: false
    PrivateMessage: false

  Staff:
    # if staff is empty
    HideAllLines: true
    # If is enabled HideAllLines
    UseReplace: true
    ReplaceWith:
    - "%prefix% Anyone from staff is online"

    PlayerName-Format: "%customname%"
    Splitter: "&7, "

  List:
    # Remove line from list broadcast, if joiner is empty
    RemoveEmptyLine: true

    PlayerName-Format: "%customname%"
    Splitter: "&7, "

  FarmingSystem:
    Use: true
    ForbiddenWorlds:
    - "spawn"

  SinglePlayerSleep: true

  # ActionBar when you have enabled vanish
  Vanish-ActionBar: true

  RAM-Percentage: false

  AntiSpam:
    Flood: true
    Caps: true

  # SPAWN, HOME, BED
  RespawnTeleport: "HOME"
  Use-RespawnTeleport: true

  TimeZone:
    Use: false
    # https://greenwichmeantime.com/time-zone
    Zone: "Europe/Prague"

  Sounds:
    Use: false
    Sound: "ENTITY_PLAYER_LEVELUP"

  Teleport:
    RequestTime: "1min"
    CommandSendLocation: false
    SafeLocation: true

  AFK:
    AutoAFK: true
    AutoKick: true
    TimeToAFK: "5min"
    TimeToKick: "10min"
    # List of commands
    Action:
      onStartAFK: []
      onStopAFK: []
      onKickAFK:
      - "kick %player% &7You were kicked for &eAFK &7longer than 15 minutes"

  Economy:
    Money: 100.0
    DisablePluginEconomy: false
    CanUseOtherEconomy: true
    BalanceTop: "&e%position%. &7%playername% &7(&e$%money%&7)"
    Log: false
    MultiEconomy:
      Use: false
      Types:
        default:
        - "world"
        - "world_nether"
        - "world_the_end"

  AutoMessage:
    Use: true
    MinimalPlayers: 1
    Interval: "5min"
    Random: true
    # - "{"text":"&0[&e&lINFO&0] &7ServerControlReloaded created by &nDevTec"}"
    UseJson: false
    Messages:
    - "&0[&e&lINFO&0] &7ServerControlReloaded created by &nDevTec"
    - "&0[&e&lINFO&0] &720% Bugs free"
    - "&0[&e&lINFO&0] &7Online players &e%online%&7/&e%max_players%"
    - "&0[&e&lINFO&0] &7You found a bug ? Report it to https://github.com/TheDevTec/ServerControlReloaded"
    - "&0[&e&lINFO&0] &7Do you like our plugin? Write a comment on the https://www.spigotmc.org/resources/71147"

  VIPSlots:
    Use: true
    AddSlots: false
    SlotsToAdd: 5
    KickWhenFullServer: true
    VIPJoinBroadcast: false
    Text:
      Kick: "&7Buy &eVIP &7on our website and get access to this &ereserved slot"
      BroadcastVIPJoin: "&eVIP player joined to the server"
      FullServer: "&7We are sorry, but all &eVIP Slots &7are in use"

  Cooldowns:
    Chat:
      Use: false
      Time: 2
    Commands:
      Use: false
      Time: 3
      PerCommand:
        Use: false
        # Command:Time
        List:
        - "Heal:300"
        - "Feed:150"

  CommandsBlocker:
    Use: false
    PerWorld:
      mine_world:
      - "res"
      - "residence"
    List:
    - "pl"
    - "version"
    - "ihasbukkit"
    - "spigot"

  StaffList:
  - "owner"
  - "admin"
  - "helper"
  - "builder"

  Colors:
    Economy:
      Plus: "&a"
      Minus: "&c"
      Zero: "&e"
    Sign:
      Use: true
      Required-Permission: true
      Permission:
        Gradient: "SCR.Other.Sign.Gradient" 
        Color: "SCR.Other.Sign.Color"
        Format: "SCR.Other.Sign.Format"
        Magic: "SCR.Other.Sign.Magic"
        Rainbow: "SCR.Other.Sign.Rainbow"
        HEX: "SCR.Other.Sign.HEX"
    Chat:
      Use: true
      Required-Permission: true
      Permission:
        Gradient: "SCR.Other.Chat.Gradient"
        Color: "SCR.Other.Chat.Color"
        Format: "SCR.Other.Chat.Format"
        Magic: "SCR.Other.Chat.Magic"
        Rainbow: "SCR.Other.Chat.Rainbow"
        HEX: "SCR.Other.Chat.HEX"

  WarningSystem:
    Reload:
      Use: true
      PauseTime: 5
      Process:
      - "&8****** &4Reload &8******"
      - "&7Server is reloading..."
      - "&8****** &4Reload &8******"
      Cancelled:
      - "&8****** &4Reload &8******"
      - "&7Server reload cancelled"
      - "&8****** &4Reload &8******"
      Messages:
      - "&8****** &4Reload &8******"
      - "&7Reloading of server in &e%time%"
      - "&8****** &4Reload &8******"
    Restart:
      Use: true
      PauseTime: 15
      Process:
      - "&8****** &4Restart &8******"
      - "&7Server is restarting..."
      - "&8****** &4Restart &8******"
      Cancelled:
      - "&8****** &4Restart &8******"
      - "&7Server restart cancelled"
      - "&8****** &4Restart &8******"
      Messages:
      - "&8****** &4Restart &8******"
      - "&7Restart of server in &e%time%"
      - "&8****** &4Restart &8******"
      Commands:
      - "send * lobby"
      Kick: "&cServer is restarting"
    Stop:
      Use: true
      PauseTime: 15
      Process:
      - "&8****** &4Shutdown &8******"
      - "&7Shutting down the server..."
      - "&8****** &4Shutdown &8******"
      Cancelled:
      - "&8****** &4Shutdown &8******"
      - "&7Server shutdown cancelled"
      - "&8****** &4Shutdown &8******"
      Messages:
      - "&8****** &4Shutdown &8******"
      - "&7Shutdown of server in &e%time%"
      - "&8****** &4Shutdown &8******"
      Commands:
      - "send * lobby"
      Kick: "&cServer closed"

  Maintenance:
    Enabled: false
    KickMessages:
    - "&8=-=-=-=-=-= &eMaintenance Mode &8=-=-=-=-=-="
    - "&7We are sorry &e%player%&7, the server is currently under maintenance mode"
    - "&7Website: &ewww.example.com"
    - "&7Discord: &ediscord.link"

  Codes:
    Use: false
    Message: "%prefix% &7Congratulation, you found secret code: &e%code%"
    List:
    - "ServerControlReloaded"
    - "TheAPI"
    - "DevTec"
    - "2019"
    Random-Command:
    - "eco give %player% 50"
    - "eco give %player% 150"
    - "give %player% diamond 2"
    - "give %player% iron_block 1"
    - "xp give %player% 150"
    Commands:
    - "eco give %player% 25"

  PlayTime:
    # if you dont't want to count AF time as play time (also apply for PlayTime rewards)
    UseAfkTime: false
    # If you want to use default minecraft palytime statistics turn this off
    UseCustomPlayTime: true

  Disallowed-Items:
    Use: false
    Worlds:
   #   Creative: 
   #   - "Bedrock"
   #   - "TNT"
   #   - "TNT_Minecart"
      world:
      -  "Bedrock"
      world_nether:
      - "Bedrock"
      world_the_end:
      - "Bedrock"

  serverlist:
    # Modify ServerListPingEvent
    enabled: true
    # selection: example
    selection: normal

    normal:
      motd: 
        0: "&7This is normal motd"
        1: "&7Created via &eSCR &7plugin"
      icon: "server-icon.png"
      players:
        # list: []
        hide-vanished: true
        playername-format: "%customname%"
        # Fake online players count
        online: "%online%"
        # Fake max players
        max: "%max_players%"
      # Leave empty (serverversion: "") for default
      serverversion: ""
      # Leave -1 for current protocol
      protocol: -1
    example:
      motd: 
        0: "&7This is example motd 2"
        1: "&7Created via &eSCR &7plugin"
      icon: "server-icon.png"
      players:
        hide-vanished: false
        playername-format: "%customname%"
        list:
        - "&6Online players: &e%online%"
        - "&6Online staff: &e%staff%"
        # Fake online players count
        online: "%online%"
        # Fake max players
        max: "%math{%online%+1}%"
      # Leave empty (serverversion: "") for default
      serverversion: "&aJOIN TO US --->                      "
      # Leave -1 for current protocol
      protocol: 0
    maintenance:
      # If is enabled maintenance mode & this option, motd, players text & serverversion will be automatically changed to this settings
      use: true
      motd: 
        0: ""
        1: "&cServer is under maintenance"
      # Icon: "maintenance-icon.png"
      icon: "server-icon.png"
      players:
        hide-vanished: false
        playername-format: "%customname%"
        list:
        - "&cServer is under maintenance,"
        - "&cTry again later.."
        # Fake online players count
        online: 0
        # Fake max players
        max: 0
      # Leave empty (serverversion: "") for default
      serverversion: "&4MAINTENANCE"
      # Leave -1 for current protocol
      protocol: 0

Homes:
  #GroupName: amount
  default: 3
 # vip: 5
 # owner: 10

Format:
  SocialSpy: "&a[&2SP | &6%player% &8>> &e%target%&a] &d%message%"
  Mail: "&e%player% &7: &e%message%"
  Time: "HH:mm:ss"
  Date: "dd.MM.yyyy"
  DateWithTime: "dd.MM.yyyy HH:mm:ss"
  Broadcast: "&0[&4Broadcast&0] &a%message%"
  PrivateMessageTo: "&8(&7You -> &e%to%&8)&7: &e%message%"
  PrivateMessageFrom: "&8(&e%from% -> &7You&8)&7: &e%message%"
  HelpOp: "&0[&4HelpOp&0] &7%sender%&7: &c%message%"

ChatFormat:
  enabled: true
  global:
    options:
      enabled: true
      json: false
    chat: "&f<%playername%&f&r> %message%"
    name: "%player%"
 # group:
 #   default:
 #     options:
 #       enabled: true
 #       json: false
 #     chat: "%playername% &8> &f%message%"
 #     name: "&7default &f%player%"
 # user:
 #  <nickname>:
 #    options:
 #      enabled: true
 #      json: false
 #    chat: "%playername% &8> &e%message%"
 #    name: "&cCustom&4Prefix &b%player%"
 #  group:
 #    <group>:
 #      options:
 #        enabled: true
 #        json: false
 #      chat: "%playername% &8> &5%message%"
 #      name: "&dHelper &9%player%"
 # world:
 #  <world>:
 #    options:
 #      enabled: true
 #      json: false
 #    global:
 #      chat: "%playername% &8> &d%message%"
 #      name: "&0[&b%world%&0] &3%player%"
 #    user:
 #      <nickname>:
 #        options:
 #          enabled: true
 #          json: false
 #        chat: "%playername% &8> &e%message%"
 #        name: "&cCustom&4Prefix &b%player%"
 #    group:
 #      <group>:
 #        options:
 #          enabled: true
 #          json: false
 #        chat: "%playername% &8> &3%message%"
 #        name: "&cAdmin &6%player%"

CountryBlocker:
  Enabled: false
  List:
    - "us"
    - "se"
    - "de"
  Whitelist:
    - "petulikan1"
    - "StraikerinaCZ"
  KickMessage: "&cYour country is currently blocked! &eContact admins for whitelist"

# Types: REGEX, CONTAINS, EQUALS, STARTS_WITH, ENDS_WITH
# Regex flags: CASE_INSENSITIVE, COMMENTS, CANON_EQ, DOTALL, LITERAL, MULTILINE, UNICODE_CASE, UNICODE_CHARACTER_CLASS, UNIX_LINES
Rules:
  antiSwear_idiot:
    # Example: "What an idiot" -> "What an good boy"
    Type: "REGEX"
    # idiot -> 1d1ot -> 1d10t
    Text: "[i1]+[ ]*[d]+[ ]*[i1]+[ ]*[o0]+[ ]*[t]+"
    Replacement:
      Use: true
      # replace word "idiot" with "*****"
      Text: "*****"
 # antiSpam_d:
 #   Type: "REGEX"
 #   Text: "d{5}"
 #   Replacement:
 #     Use: true
 #     Text: "d"
 # antiAd_ip:
 #   Type: "REGEX"
 #   Text: "[0-9 ]+[.:_ ][0-9 ]+[ .:_][0-9 ]+[.:_ ][0-9 ]+(:[0-9 ]+)*"
 #   Replacement:
 #     Use: false
 #     Text: "ANTIAD"
 # antiAd_web:
 #   Type: "REGEX"
 #   Text: "(www[\.:?_\//][^ ]{4,}|https?[\.:?_\//]\/\/[^ ]{4,}|[A-Za-z0-9,?:!_/()\[\]+*-]{2,30}[ ]*\.[ ]*[A-Za-z0-9,?:!_/()\[\]+*-]{3,30}([ ]*\.[ ]*[A-Za-z0-9.,?:!_/()\[\]+*-]{2,30})*)"
 #   Replacement:
 #     Use: false
 #     Text: "ANTIAD"

BanSystem:
  TempMute:
    Text: "&7You are temp-muted for &e%reason%&7 on &e%time%"
    Time: "1h"
    Reason: "None"
    ForbiddenCommands:
    - "msg "
    - "pm "
    - "tell "
    - "w "
  Mute:
    Text: "&7You are muted for &e%reason%"
    Reason: "None"
    ForbiddenCommands:
    - "msg "
    - "pm "
    - "tell "
    - "w "
  Ban:
    Text: "&7You are banned for &e%reason%\n&7www.example.com"
    Reason: "None"
  TempBan:
    Text: "&7You are temp-banned for &e%reason%&7 on &e%time%\n&7www.example.com"
    Time: "1h"
    Reason: "None"
  Kick:
    Text: "&7You are kicked for &e%reason%\n&7www.example.com"
    Reason: "None"
  BanIP:
    Text: "&7You are ip-banned for &e%reason%\n&7www.example.com"
    Reason: "None"
  TempBanIP:
    Text: "&7You are temp-ip-banned for &e%reason%&7 on &e%time%\n&7www.example.com"
    Reason: "None"
    Time: "1h"
  TempJail:
    Text: "&7You are temp-arrested for &e%reason%&7 on &e%time%"
    Time: "1h"
    Reason: "None"
    ForbiddenCommands:
    - "spawn"
    - "home"
    - "warp"
    - "tp"
  Jail:
    Text: "&7You are arrested for &e%reason%"
    Reason: "None"
    ForbiddenCommands:
    - "spawn"
    - "home"
    - "warp"
    - "tp"
  Warn:
    Text: "&7You are warned for &e%reason%"
    Reason: "None"