# On player join
onJoin:
  # First time join to the server
  First:
    Messages:
    - "%prefix% »==========«"
    - "%prefix% Welcome on our server, &e%playername%"
    - "%prefix% Server time: &e%time%"
    - "%prefix% »==========«"
    Commands:
    - "kit %player% default"
    Broadcast:
    - "%prefix% Welcome &e%player% &7on our server!"
    - "%prefix% Player &e%player% &7joined the game"
    Text: "none"
  # Join to the server (Not first time)
  Messages:
    - "%prefix% »==========«"
    - "%prefix% Welcome back, &e%player%"
    - "%prefix% Server time: &e%time%"
    - "%prefix% »==========«"
  Text: "%prefix% Player &e%player% &7joined the game"
# On player quit
onQuit:
  Text: "%prefix% Player &e%player% &7left the game"

# On player chat event
onChat:
  Rules:
  - "1"
  - "2"

# On player send command event
onCommand:
  Rules:
  - "1"
  - "2"

# On anvil rename item event
onAnvil:
  Rules:
  - "1"
  - "2"

# On sign change event
onSign:
  Rules:
  - "1"
  - "2"

# On book edit event
onBook:
  Rules:
  - "1"
  - "2"

# On drop item event
onDropItem:
  Rules:
  - "1"
  - "2"

# On pickup item event
onPickupItem:
  Rules:
  - "1"
  - "2"