# On player join
onJoin:
  # First time join to the server
  First:
    Messages:
    - "%prefix% »==========«"
    - "%prefix% Welcome on our server, &e%playername%"
    - "%prefix% Server time: &e%time%"
    - "%prefix% »==========«"
    Commands:
    - "kit firstJoin %player%"
    Broadcast:
    - "%prefix% Welcome &e%player% &7on our server!"
    Text: "%prefix% Player &e%player% &7joined the game"
  # Join to the server (Not first time)
  Messages:
    - "%prefix% »==========«"
    - "%prefix% Welcome back, &e%player%"
    - "%prefix% Server time: &e%time%"
    - "%prefix% »==========«"
  Text: "%prefix% Player &e%player% &7joined the game"
  
# On player dead
onDeath:
  Messages: []
  Commands: []
  
# On player quit
onQuit:
  Text: "%prefix% Player &e%player% &7left the game"
  Messages: []
  Commands: []

# On player chat event
onChat:
  Rules:
  - "antiSwear_idiot"

# On player send command event
onCommand:
  Rules: []

# On anvil rename item event
onAnvil:
  Rules: []

# On sign change event
onSign:
  Rules: []

# On book edit event
onBook:
  Rules: []

# On drop item event
onDropItem:
  Rules: []

# On pickup item event
onPickupItem:
  Rules: []

# When you enable/disable vanish
onVanish:
  Enable:
    Broadcast: []
  Disable:
    Broadcast: []