# Commands:
#   help:
#     gui: "helpGui"
#     aliases:
#     - "helpmenu"
#     permission: "SCR.GUI.Help"
# GUI:
#   helpGui:
#     title: "&cHelp Menu"
#     size: 54
#     items:
#     cost: 0.0
#     takeMoney: false
#     noMoney:
#     - "left msg &cYou don't have enough money"
#       0,1,2,3,4,5,6,7,8,53,52,51,50,48,47,46,45:
#         name: "&7"
#         type: "black_stained_glass_pane"
#       49:
#         name: "&cClose"
#         lore:
#         - "&1Hello!"
#         - "&7Have a nice day"
#         type: "barrier"
#         action:
#         - "left close"
#         - "left msg &cYou have closed GUI"
