# Commands:
#   help:
#     name: "helpGui"
#     gui: "helpGui"
#     aliases:
#     - "helpmenu"
#     permission: "SCR.GUI.Help"
# GUI:
#   helpGui:
#     title: "&cHelp Menu"
#     size: 54
#     items:
#       0,1,2,3,4,5,6,7,8:
#         name: "&7"
#         type: "black_stained_glass_pane"
#       45:
#         name: "&cClose"
#         lore:
#         - "&1Hello!"
#         - "&7Have a nice day"
#         type: "barrier"
#         action:
#         - "left close"
 #        - "left msg &cYou have closed GUI"