Kits:
  firstJoin:
    # Permission to use kit
    permission: "SCR.Kit.firstJoin"
    # Time in string (1h15m, 2h.. or just number: 3600, 7200..)
    delay: 0
    # Set cost of kit in string (1k, 5.2k.. or just number: 1000, 52000..)
    cost: 0
    # List of items of kit
    items:
      # Add item to player's inventory
      add:
        0:
          type: "STONE_SWORD"
          amount: 1
          name: "&7Stone Sword"
          lore:
          - "&eStarter kit"
          enchants:
          - "UNBREAKING:1"
        1:
          type: "STONE_PICKAXE"
          amount: 1
          name: "&7Stone Pickaxe"
          lore:
          - "&eStarter kit"
          enchants:
          - "EFFICIENCY:1"
        2:
          type: "BREAD"
          amount: 16
          name: "&7Tasty bread"
          lore:
          - "&cMade with <3"
          enchants:
          - "UNBREAKING:1"
          flags:
          - "HIDE_ENCHANTS"
      # Set (Override) item in specific slot in player's inventory
      # set:
      #   0:
      #     type: "STONE_SWORD" 
      #     amount: 1
      #     name: "&7Stone Sword"
      #     lore:
      #     - "&eStarter kit"
      #     enchants:
      #     - "UNBREAKING:1"
      #   2:
      #     type: "STONE_PICKAXE" 
      #     amount: 1
      #     name: "&7Stone Pickaxe"
      #     lore:
      #     - "&eStarter kit"
      #     enchants:
      #     - "EFFICIENCY:1"