# Per player scoreboard
PerPlayer:
  StraikerinaCZ:
    # Player can't toggle this scoreboard
    Toggleable: false
    Name: "&8» &7&lCustom Scoreboard &8«"
    Lines:
    - "&7&lStats:"
    - " &8» &7Balance: &e$%money%"
    - " &8» &7Health: &e%health%"
    - " &8» &7Food: &e%food%"
    - " &8» &7Exp: &e%xp%"
    
# Per world scoreboard
PerWorld:
  RPGWorld:
    # Scoreboard in this world can't be toggled
    Toggleable: false
    Name: "&8» &7&lRPG &8«"
    Lines:
    - "&7&lStats:"
    - " &8» &7Balance: &e$%money%"
    - " &8» &7Health: &e%health%"
    - " &8» &7Food: &e%food%"
    - " &8» &7Exp: &e%xp%"

Options:
  # Enable scoreboard
  Enabled: true
  
  # Option to toggle scoreboard by command
  Toggleable: true
  
  # Time to update scoreboard
  # 20 ticks = 1s
  RefleshTick: 20

# Displayname of scoreboard
Name: "&8» &7&lInfo &8«"

# Lines in scoreboard
Lines:
- "&7&lStats:"
- " &8» &7Balance: &e$%money%"
- " &8» &7Health: &e%health%"
- " &8» &7Food: &e%food%"
- "&7&lServer:"
- " &8» &7Online: &e%online%"
- " &8» &7Time: &e%server_time%"
