Options:
  # Enable tablist
  Enabled: true
  
  # Allow sorting of tablist by vault groups
  Sorting: true
  Sorting-Groups:
  - "owner"
  - "admin"
  - "helper"
  - "builder"
  - "vip"
  - "default"
  
  Modify:
    # Modify header in tablist
    Header: true
    # Modify footer in tablist
    Footer: true
    # Modify text above player
    NameTags: true
    
    # Modify name of player in tablist
    TabListName: true
  
  RefleshTick:
    # Time to update text above player
    # 20 ticks = 1s
    Tablist: 20
    
    # Time to update tablist header, footer & playername
    # 20 ticks = 1s
    NameTag: 20

# AFK Placeholder values
AFK:
 true: " &4&l*AFK*"
 false: "&r"

# Per world tablist
PerWorld:
  RPGWorld:
    Header:
    - "&8=====» &7&lRPG Map &8«====="
    - "&7Ping: &e%ping%    &7Online: &e%online%"
    Footer:
    - "&7Health: &e%health%    &7Food: &e%food%"
    - "&7Balance: &e$%money%"

# Per player tablist
PerPlayer:
  StraikerinaCZ:
    Header:
    - "&8=====» &7&lThis is your tablist, %player% &8«====="
    - "&7Ping: &e%ping%    &7Online: &e%online%"
    Footer:
    - "&7Health: &e%health%    &7Food: &e%food%"
    - "&7Balance: &e$%money%   &7TPS: &e%tps%"

# Text above players
Header:
- "&8=====» &7&lSever Name &8«====="
- "&7Ping: &e%ping%    &7Online: &e%online%"

# Text under players
Footer:
- "&7Health: &e%health%    &7Food: &e%food%"
- "&7Balance: &e$%money%"

Groups:
  default:
    NameTag:
      Prefix: "&7default &f"
      Suffix: ""
    TabList:
      Prefix: "&7default &f"
      Suffix: "%afk%"
      Format: "%tab_prefix%%customname%%tab_suffix%"
  vip:
    NameTag:
      Prefix: "&eVIP &a"
      Suffix: ""
    TabList:
      Prefix: "&eVIP &a"
      Suffix: "%afk%"
      Format: "%tab_prefix%%customname%%tab_suffix%"
  builder:
    NameTag:
      Prefix: "&2Builder &e"
      Suffix: ""
    TabList:
      Prefix: "&2Builder &e"
      Suffix: "%afk%"
      Format: "%tab_prefix%%customname%%tab_suffix%"
  helper:
    NameTag:
      Prefix: "&5Helper &9"
      Suffix: ""
    TabList:
      Prefix: "&5Helper &9"
      Suffix: "%afk%"
      Format: "%tab_prefix%%customname%%tab_suffix%"
  admin:
    NameTag:
      Prefix: "&4Admin &6"
      Suffix: ""
    TabList:
      Prefix: "&4Admin &6"
      Suffix: "%afk%"
      Format: "%tab_prefix%%customname%%tab_suffix%"
  owner:
    NameTag:
      Prefix: "&4Owner &f"
      Suffix: ""
    TabList:
      Prefix: "&4Owner &f"
      Suffix: "%afk%"
      Format: "%tab_prefix%%customname%%tab_suffix%"
      